version: '1'
services:
  nest:
    restart: always
    build: .
    image: spidervs/nodejs2022q4:nest
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    volumes:
      - ./src:/usr/app/src

  postgres:
    restart: always
    build: ./database/
    image: spidervs/nodejs2022q4:postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database/data:/var/lib/postgresql/data

  # pgadmin:
  #       image: dpage/pgadmin4
  #       environment:
  #           PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #           PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #       ports:
  #           - ${PGADMIN_PORT}:80
  #       depends_on:
  #           - postgres
