services:
  nest:
    restart: always
    build: .
    # You can use next line to download the latest version of the image and run it. Comment out the previous line.
    image: spidervs/nodejs2022q4:nest-app
    ports:
      - ${PORT}:${PORT}
    networks:
      - front-tier
      - back-tier
    depends_on:
      - db
    environment:
      - PORT=${PORT}
    volumes:
      - ./src:/usr/app/src

  db:
    restart: always
    build: ./database/
    # You can use next line to download the latest version of the image and run it. Comment out the previous line.
    image: spidervs/nodejs2022q4:postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - back-tier
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - ${PGADMIN_PORT}:80
        networks:
          - back-tier
        volumes:
          - pgadmin-data:/var/lib/pgadmin
        depends_on:
            - db

volumes:
  pgdata:
  # pglogs:
  pgadmin-data:

networks:
  front-tier: {}
  back-tier: {}
